# Generated by Django 5.1.7 on 2025-03-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'QR User', 'verbose_name_plural': 'QR Users'},
        ),
    ]
